// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

// BỘC BAY CÁI CLASS FirebaseOptions Ở KHÚC NÀY RỒI NHÉ!

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHU7CFEh8_VXJzaxilINguTdM5ue8INFo',
    appId: '1:617886373200:web:2503484d96c46cf4480855',
    messagingSenderId: '617886373200',
    projectId: 'selling-ap',
    authDomain: 'selling-ap.firebaseapp.com',
    storageBucket: 'selling-ap.firebasestorage.app',
    measurementId: 'G-38VESWP42H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOZJATHuIsKpzTaMXU7nmcMXCXo-YQ8oM',
    appId: '1:617886373200:android:8f2d07465aa097e4480855',
    messagingSenderId: '617886373200',
    projectId: 'selling-ap',
    storageBucket: 'selling-ap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwzeeyHRZ7dCuH_9ZyJZf-IRIH-t5Y0qE',
    appId: '1:617886373200:ios:6a269a97cd4a6aee480855',
    messagingSenderId: '617886373200',
    projectId: 'selling-ap',
    storageBucket: 'selling-ap.firebasestorage.app',
    iosBundleId: 'com.example.projectFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwzeeyHRZ7dCuH_9ZyJZf-IRIH-t5Y0qE',
    appId: '1:617886373200:ios:6a269a97cd4a6aee480855',
    messagingSenderId: '617886373200',
    projectId: 'selling-ap',
    storageBucket: 'selling-ap.firebasestorage.app',
    iosBundleId: 'com.example.projectFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHU7CFEh8_VXJzaxilINguTdM5ue8INFo',
    appId: '1:617886373200:web:fbb497803f9e9b47480855',
    messagingSenderId: '617886373200',
    projectId: 'selling-ap',
    authDomain: 'selling-ap.firebaseapp.com',
    storageBucket: 'selling-ap.firebasestorage.app',
    measurementId: 'G-5N2V18YYWM',
  );
}
